export const SAVE_TASK_REQUEST = 'SAVE_TASK_REQUEST'
export const FETCH_TASK_REQUEST = 'FETCH_TASK_REQUEST'
export const UPDATE_TASK_REQUEST = 'UPDATE_TASK_REQUEST'
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'
export const TASK_SUCCESS = 'TASK_SUCCESS'
export const TASK_FAILURE = 'TASK_FAILURE'

export const FETCH_PRIORITIES_REQUEST = 'FETCH_PRIORITIES_REQUEST';
export const PRIORITIES_SUCCESS = 'PRIORITIES_SUCCESS';
export const PRIORITIES_FAILURE = 'PRIORITIES_FAILURE';

export const FETCH_STATUS_REQUEST = 'FETCH_STATUS_REQUEST';
export const STATUS_SUCCESS = 'STATUS_SUCCESS';
export const STATUS_FAILURE = 'STATUS_FAILURE';